# 项目信息
project_name: xxx 项目测试

# 测试执行人
tester: 小小月芽儿

# 环境信息：测试、正式、预发布地址
env: test
host: 127.0.0.1

# 测试报告通知类型：0表示默认邮件、1表示钉钉
notification_type: 0

# 测试用例缓存地址: 0表示本地缓存、1表示redis缓存
cache_type: 0

# 是否开启日志,true表示开启，false表示不开启
log: false

# mysql 连接信息
mysql:
  host: '127.0.0.1' # MySQL服务端的IP地址
  port: 3306  # MySQL默认PORT地址(端口号)
  user: 'root'  # 用户名
  password: '123456'  # 密码,也可以简写为passwd
  database: 'test' # 库名称,也可以简写为db
  charset: 'utf8'


# Email 信息
email:
  host: smtp.qq.com     #邮箱服务
  user: 123456@qq.com   # 邮箱用户名
  key:  qweefedvdgrbf   # 邮箱鉴权 key
  recevies: 12345678@qq.com   # 收件人，可以配置多个收件人
#  recevies:
#   - 12345678@qq.com

# redis 缓存配置
redis:
  host: '127.0.0.1'
  port: 6379
  db: 0

# 钉钉通知信息
ding_talk:
  webhook: WQEEWFREWGFDG
  secret: QWEWRWER

