info:
  url: /api/sys/operation/audit/record/
  method: get


cases:
  - id: record_01
    is_run: true
    title: "获取系列"
    headers:
      Content-Type: application/json
      Authorization: $.depends_data.depends_data
    cookies:
    is_depend: true
    depends_data:
      - depend_case_id: login_01
        depends_case_data:
         - depends_data_type: response
           json_path: $.data.access_token
    request_type: params
    data:
      body:
        start: 0
        limit: 10
        filter: ''
        sort: ''
      params:
    encode:
        - $.data.body.filter
        - $.data.body.sort
    assert:
      assert_type: response
      actual: $.message
      type: ==
      expect: "success"




